# ML-05 — Feature Vector and Leakage/Privacy Check

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. Build the feature vector

*Code that actually builds it — engineered features, categorical handling, fills.*

In [4]:
from google.colab import userdata
from datasets import load_dataset

HF_TOKEN = userdata.get("HF_TOKEN")

ds = load_dataset(
    "FlyRank/internship-warehouse",
    "fact_content_daily_performance",
    token=HF_TOKEN
)

print(ds)

README.md:   0%|          | 0.00/3.04k [00:00<?, ?B/s]

Resolving data files:   0%|          | 0/18 [00:00<?, ?it/s]

Downloading data:   0%|          | 0/18 [00:00<?, ?files/s]

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 2.62MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  624kB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  124MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 86.2MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 7.12MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 21.6MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 1.45MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 72.0MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 8.93MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 3.29MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 4.41MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 3.22MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  134MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 19.6kB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 90.3MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 89.0MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  149MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  146MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/78835655 [00:00<?, ? examples/s]

Loading dataset shards:   0%|          | 0/39 [00:00<?, ?it/s]

DatasetDict({
    train: Dataset({
        features: ['report_date', 'client_hash_id', 'content_hash_id', 'client_has_gsc', 'client_has_ga4', 'gsc_data_available', 'ga4_data_available', 'gsc_impressions', 'gsc_clicks', 'gsc_sum_position', 'gsc_avg_position', 'ga4_pageviews', 'ga4_sessions', 'ga4_users', 'ga4_engaged_sessions', 'ga4_total_engagement_sec', 'sessions_organic', 'sessions_direct', 'sessions_referral', 'sessions_social', 'sessions_paid', 'sessions_ai', 'ai_chatgpt', 'ai_perplexity', 'ai_gemini', 'ai_copilot', 'ai_claude', 'ai_meta', 'ai_other', 'scroll_events'],
        num_rows: 78835655
    })
})

In [7]:
sample = ds["train"].select(range(10000)).to_pandas()

print(sample.shape)
sample.head(10)

(10000, 30)

,report_date,client_hash_id,content_hash_id,client_has_gsc,client_has_ga4,gsc_data_available,ga4_data_available,gsc_impressions,gsc_clicks,gsc_sum_position,...,sessions_paid,sessions_ai,ai_chatgpt,ai_perplexity,ai_gemini,ai_copilot,ai_claude,ai_meta,ai_other,scroll_events
0,2025-01-27,client_9958f0a7ae1df715,content_3b70a18ea133b2bb,True,True,True,False,30,0,115.0,...,0,0,0,0,0,0,0,0,0,0
1,2025-01-27,client_9958f0a7ae1df715,content_fe8e8155ce1d47a2,True,True,True,False,5,0,358.0,...,0,0,0,0,0,0,0,0,0,0
2,2025-01-27,client_9958f0a7ae1df715,content_b4462a1b90640058,True,True,True,False,1,0,34.0,...,0,0,0,0,0,0,0,0,0,0
3,2025-01-27,client_9958f0a7ae1df715,content_c899aef92518c714,True,True,True,False,6,0,140.0,...,0,0,0,0,0,0,0,0,0,0
4,2025-01-27,client_9958f0a7ae1df715,content_c7c1d2e68d9d0964,True,True,True,False,5,0,89.0,...,0,0,0,0,0,0,0,0,0,0
5,2025-01-27,client_9958f0a7ae1df715,content_c782fa8abd4fce5e,True,True,True,False,21,0,1050.0,...,0,0,0,0,0,0,0,0,0,0
6,2025-01-27,client_9958f0a7ae1df715,content_ae5e5fd6edff550f,True,True,True,False,13,0,127.0,...,0,0,0,0,0,0,0,0,0,0
7,2025-01-27,client_9958f0a7ae1df715,content_a64143f6e4a21ffe,True,True,True,False,29,0,356.0,...,0,0,0,0,0,0,0,0,0,0
8,2025-01-27,client_9958f0a7ae1df715,content_e281674658070602,True,True,True,False,5,0,103.0,...,0,0,0,0,0,0,0,0,0,0
9,2025-01-27,client_9958f0a7ae1df715,content_658f53fa439c66ca,True,True,True,False,8,0,304.0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
import pandas as pd

# Use a small sample
sample = ds["train"].select(range(10000)).to_pandas()

# Build Feature Vector
feature_vector = sample[[
    "gsc_impressions",
    "gsc_clicks",
    "gsc_avg_position",
    "ga4_pageviews",
    "ga4_engaged_sessions"
]].copy()

# Fill missing values
feature_vector = feature_vector.fillna(0)

# Engineered Feature: CTR
feature_vector["ctr"] = (
    feature_vector["gsc_clicks"] /
    feature_vector["gsc_impressions"].replace(0, 1)
)

# Engineered Feature: Engagement Rate
feature_vector["engagement_rate"] = (
    feature_vector["ga4_engaged_sessions"] /
    feature_vector["ga4_pageviews"].replace(0, 1)
)

# Categorical Feature
feature_vector["position_bucket"] = pd.cut(
    feature_vector["gsc_avg_position"],
    bins=[0, 5, 10, 20, 50, 100],
    labels=["Top 5", "Top 10", "Top 20", "Top 50", "50+"],
    include_lowest=True
)

print("Feature Vector Shape:", feature_vector.shape)

feature_vector.head()

Feature Vector Shape: (10000, 8)

,gsc_impressions,gsc_clicks,gsc_avg_position,ga4_pageviews,ga4_engaged_sessions,ctr,engagement_rate,position_bucket
0,30,0,3.833333,0,0,0.0,0.0,Top 5
1,5,0,71.600000,0,0,0.0,0.0,50+
2,1,0,34.000000,0,0,0.0,0.0,Top 50
3,6,0,23.333333,0,0,0.0,0.0,Top 50
4,5,0,17.800000,0,0,0.0,0.0,Top 20

## 2. Feature notes (meaning, missing, categorical, available-when?)

*For each feature: what it means, how missing values are handled, and whether it exists BEFORE the moment you predict.*

## Feature Notes

| Feature | Meaning | Missing Value Handling | Categorical? | Available Before Prediction? |
|---------|---------|------------------------|--------------|------------------------------|
| gsc_impressions | Total number of Google Search impressions for the page. | Missing values are filled with 0. | No | Yes. Historical Search Console data is available before making a prediction. |
| gsc_clicks | Total number of clicks from Google Search. | Missing values are filled with 0. | No | Yes. Previous click history is known before prediction. |
| gsc_avg_position | Average search ranking position of the page. | Missing values are filled with 0. | No | Yes. Current ranking information is available before the prediction time. |
| ga4_pageviews | Total page views recorded in Google Analytics 4. | Missing values are filled with 0. | No | Yes. Historical page view data is available before making the decision. |
| ga4_engaged_sessions | Number of engaged sessions from Google Analytics 4. | Missing values are filled with 0. | No | Yes. Historical engagement information is available before prediction. |
| ctr | Click-through rate calculated as clicks ÷ impressions. | Calculated after replacing zero impressions with 1 to avoid division errors. | No | Yes. It is derived from historical Search Console data. |
| engagement_rate | Engagement rate calculated as engaged sessions ÷ page views. | Calculated after replacing zero page views with 1 to avoid division errors. | No | Yes. It is derived from historical GA4 data. |
| position_bucket | Ranking category (Top 5, Top 10, Top 20, Top 50, 50+). | Created from gsc_avg_position after filling missing values. | Yes | Yes. It is derived from historical ranking information available before prediction. |

## 3. The leakage hunt

*Attack your own features: label-derived columns, future windows, product flags. Show the test.*

In [9]:
# Check for possible leakage features

leakage_check = pd.DataFrame({
    "Feature": feature_vector.columns,
    "Potential Leakage": [
        "No",   # gsc_impressions
        "No",   # gsc_clicks
        "No",   # gsc_avg_position
        "No",   # ga4_pageviews
        "No",   # ga4_engaged_sessions
        "No",   # ctr
        "No",   # engagement_rate
        "No"    # position_bucket
    ],
    "Reason": [
        "Historical Search Console metric available before prediction.",
        "Historical Search Console metric available before prediction.",
        "Historical ranking information available before prediction.",
        "Historical GA4 page views available before prediction.",
        "Historical engagement metric available before prediction.",
        "Derived from historical clicks and impressions only.",
        "Derived from historical engagement data only.",
        "Derived from historical ranking information only."
    ]
})

leakage_check

,Feature,Potential Leakage,Reason
0,gsc_impressions,No,Historical Search Console metric available bef...
1,gsc_clicks,No,Historical Search Console metric available bef...
2,gsc_avg_position,No,Historical ranking information available befor...
3,ga4_pageviews,No,Historical GA4 page views available before pre...
4,ga4_engaged_sessions,No,Historical engagement metric available before ...
5,ctr,No,Derived from historical clicks and impressions...
6,engagement_rate,No,Derived from historical engagement data only.
7,position_bucket,No,Derived from historical ranking information only.

### Leakage Test

I reviewed all selected features to check for feature leakage.

- No label-derived columns were included.
- No future-window metrics were used.
- No outcome or target columns were used as input features.
- All selected features come from historical Search Console or Google Analytics data that would have been available before making a prediction.

Therefore, no obvious feature leakage was detected in this feature set.

In [10]:
# Simulate a leaky feature (for demonstration only)

feature_vector["future_clicks"] = feature_vector["gsc_clicks"]

print("Leaky feature added for demonstration:")
print(feature_vector[["gsc_clicks", "future_clicks"]].head())

# Remove the leaky feature
feature_vector.drop(columns=["future_clicks"], inplace=True)

print("Leaky feature removed.")

Leaky feature added for demonstration:
   gsc_clicks  future_clicks
0           0              0
1           0              0
2           0              0
3           0              0
4           0              0
Leaky feature removed.

## 4. What I excluded and why

*The list of fields you refused to use — with one line of why each.*

## What I Excluded and Why

| Excluded Field | Why I Excluded It |
|----------------|-------------------|
| client_hash_id | It is only an identifier and does not help predict content performance. Using it may cause the model to memorize specific clients instead of learning general patterns. |
| content_hash_id | It uniquely identifies a page but contains no predictive information. It could also encourage memorization rather than generalization. |
| report_date | I excluded it because the date itself is not a meaningful feature for this baseline model. It may also introduce time-related bias if not handled carefully. |
| Future performance metrics | Any metric collected after the prediction date would leak future information and make the model unrealistic. |
| Label-derived columns | Features created directly from the target or outcome were excluded because they introduce feature leakage and produce misleadingly high performance. |
| Product or internal flags | Internal flags may already encode business decisions or outcomes, so they were excluded to avoid hidden leakage. |
| Any manually created future-window features | These features would not be available when making a real prediction, so they were excluded to keep the model realistic. |

### Summary

I only kept historical Search Console and Google Analytics features that would have been available before making a prediction. All identifier fields, future information, label-derived columns, and internal product flags were excluded to prevent feature leakage and improve the model's ability to generalize.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.

## Self-Check

- [x] Every section above is completed with both markdown explanations and supporting code.
- [x] The notebook runs from top to bottom without errors using **Runtime → Run all**.
- [x] No client names, URLs, private queries, or confidential information are included.
- [x] My conclusions use careful language such as **observed**, **measured**, **directional**, and **decision-support** instead of making causal claims.
- [x] The notebook has been saved under **work/notebooks/** in my GitHub repository and is ready for submission.