# ML-05 — Feature Vector and Leakage/Privacy Check

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. Build the feature vector

*Code that actually builds it — engineered features, categorical handling, fills.*

In [1]:
from google.colab import userdata
from datasets import load_dataset
import pandas as pd

HF_TOKEN = userdata.get("HF_TOKEN")

ds = load_dataset(
    "FlyRank/internship-warehouse",
    "fact_content_daily_performance",
    token=HF_TOKEN
)

# FIX: shuffle before sampling so this notebook's exploration reflects
# many clients, not whatever sorts first in storage.
sample = ds["train"].shuffle(seed=42).select(range(10000)).to_pandas()

print(sample.shape)
print("Unique clients in sample:", sample["client_hash_id"].nunique())
sample.head()

README.md:   0%|          | 0.00/3.04k [00:00<?, ?B/s]

Resolving data files:   0%|          | 0/18 [00:00<?, ?it/s]

Downloading data:   0%|          | 0/18 [00:00<?, ?files/s]

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 86.2MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 1.45MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 19.6kB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 7.12MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 4.41MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 8.93MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 90.3MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  124MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 3.29MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 21.6MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  624kB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  134MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 3.22MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 2.62MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 89.0MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 72.0MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  149MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  146MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/78835655 [00:00<?, ? examples/s]

Loading dataset shards:   0%|          | 0/39 [00:00<?, ?it/s]

(10000, 30)
Unique clients in sample: 69

,report_date,client_hash_id,content_hash_id,client_has_gsc,client_has_ga4,gsc_data_available,ga4_data_available,gsc_impressions,gsc_clicks,gsc_sum_position,...,sessions_paid,sessions_ai,ai_chatgpt,ai_perplexity,ai_gemini,ai_copilot,ai_claude,ai_meta,ai_other,scroll_events
0,2025-12-09,client_ff644d8251367cbb,content_d351e0cee47ac00c,True,True,False,False,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2025-12-27,client_e547b89c05043229,content_01a8f5a4ba3c2c92,True,True,False,True,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2026-04-02,client_08a6a72ff48e62c0,content_b9c8062233293ced,True,False,False,None,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-04-14,client_e5c2aa26a8598242,content_c75991003927d734,True,True,True,False,145.0,0.0,3763.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2025-12-01,client_9958f0a7ae1df715,content_323998d3de254f5e,True,True,True,False,4.0,0.0,16.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# 1. Build the feature vector

In [2]:
feature_vector = sample[[
    "gsc_impressions",
    "gsc_clicks",
    "gsc_avg_position",
    "ga4_pageviews",
    "ga4_engaged_sessions"
]].copy()

feature_vector = feature_vector.fillna(0)

feature_vector["ctr"] = (
    feature_vector["gsc_clicks"] / feature_vector["gsc_impressions"].replace(0, 1)
)

feature_vector["engagement_rate"] = (
    feature_vector["ga4_engaged_sessions"] / feature_vector["ga4_pageviews"].replace(0, 1)
)

feature_vector["position_bucket"] = pd.cut(
    feature_vector["gsc_avg_position"],
    bins=[0, 5, 10, 20, 50, 100],
    labels=["Top 5", "Top 10", "Top 20", "Top 50", "50+"],
    include_lowest=True
)

print("Feature Vector Shape:", feature_vector.shape)
feature_vector.head()

Feature Vector Shape: (10000, 8)

,gsc_impressions,gsc_clicks,gsc_avg_position,ga4_pageviews,ga4_engaged_sessions,ctr,engagement_rate,position_bucket
0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,Top 5
1,0.0,0.0,0.000000,1.0,0.0,0.0,0.0,Top 5
2,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,Top 5
3,145.0,0.0,25.951724,0.0,0.0,0.0,0.0,Top 50
4,4.0,0.0,4.000000,0.0,0.0,0.0,0.0,Top 5

## 2. Feature notes (meaning, missing, categorical, available-when?)

*For each feature: what it means, how missing values are handled, and whether it exists BEFORE the moment you predict.*

## 2. Feature notes

| Feature | Meaning | Missing Value Handling | Categorical? | Available Before Prediction? |
|---|---|---|---|---|
| gsc_impressions | Google Search impressions | Filled with 0 | No | Yes |
| gsc_clicks | Google Search clicks | Filled with 0 | No | Yes — **but see the conditional leakage note below** |
| gsc_avg_position | Average search ranking position | Filled with 0 | No | Yes — **but see the conditional leakage note below** |
| ga4_pageviews | GA4 page views | Filled with 0 | No | Yes |
| ga4_engaged_sessions | GA4 engaged sessions | Filled with 0 | No | Yes |
| ctr | clicks / impressions | Zero-impression rows use 1 in denominator | No | Yes, derived |
| engagement_rate | engaged sessions / pageviews | Zero-pageview rows use 1 in denominator | No | Yes, derived |

## 3. The leakage hunt

*Attack your own features: label-derived columns, future windows, product flags. Show the test.*

In [3]:
# ------------------------------------------------------------
# Leakage check, v2: available-before-prediction check PLUS an explicit
# flag for "this field is a strong candidate for defining a future label"
# ------------------------------------------------------------

leakage_check = pd.DataFrame({
    "Feature": feature_vector.columns,
    "Available_Before_Prediction": [
        "Yes", "Yes", "Yes", "Yes", "Yes", "Yes", "Yes", "Yes"
    ],
    "Candidate_Label_Defining_Field": [
        "No",   # gsc_impressions
        "YES",  # gsc_clicks  <- flagged: commonly used to define "underperforming" labels
        "YES",  # gsc_avg_position <- flagged: commonly used to define "underperforming" labels
        "No",   # ga4_pageviews
        "No",   # ga4_engaged_sessions
        "No",   # ctr (derived from clicks, inherits the flag if clicks defines the label)
        "No",   # engagement_rate
        "No",   # position_bucket (derived from avg_position, inherits the flag)
    ],
    "Note": [
        "Safe as a feature under any target definition seen so far.",
        "SAFE AS A FEATURE ONLY IF NOT ALSO USED TO BUILD THE TARGET. Must be re-checked once a target is defined.",
        "SAFE AS A FEATURE ONLY IF NOT ALSO USED TO BUILD THE TARGET. Must be re-checked once a target is defined.",
        "Safe as a feature under any target definition seen so far.",
        "Safe as a feature under any target definition seen so far.",
        "Derived from gsc_clicks — inherits its flag.",
        "Safe as a feature under any target definition seen so far.",
        "Derived from gsc_avg_position — inherits its flag.",
    ]
})

display(leakage_check)

print()
print("ACTION ITEM for whoever defines the target in a later notebook:")
print("If the target formula uses gsc_clicks and/or gsc_avg_position (or any")
print("column derived from them, like ctr or position_bucket), those columns")
print("MUST be excluded from the feature set used to train a model on that target.")

,Feature,Available_Before_Prediction,Candidate_Label_Defining_Field,Note
0,gsc_impressions,Yes,No,Safe as a feature under any target definition ...
1,gsc_clicks,Yes,YES,SAFE AS A FEATURE ONLY IF NOT ALSO USED TO BUI...
2,gsc_avg_position,Yes,YES,SAFE AS A FEATURE ONLY IF NOT ALSO USED TO BUI...
3,ga4_pageviews,Yes,No,Safe as a feature under any target definition ...
4,ga4_engaged_sessions,Yes,No,Safe as a feature under any target definition ...
5,ctr,Yes,No,Derived from gsc_clicks — inherits its flag.
6,engagement_rate,Yes,No,Safe as a feature under any target definition ...
7,position_bucket,Yes,No,Derived from gsc_avg_position — inherits its f...

ACTION ITEM for whoever defines the target in a later notebook:
If the target formula uses gsc_clicks and/or gsc_avg_position (or any
column derived from them, like ctr or position_bucket), those columns
MUST be excluded from the feature set used to train a model on that target.

### Leakage Test

I reviewed all selected features to check for feature leakage.

- No label-derived columns were included.
- No future-window metrics were used.
- No outcome or target columns were used as input features.
- All selected features come from historical Search Console or Google Analytics data that would have been available before making a prediction.

Therefore, no obvious feature leakage was detected in this feature set.

## 4. What I excluded and why

*The list of fields you refused to use — with one line of why each.*

## 4. What I excluded and why

| Excluded Field | Why |
|---|---|
| client_hash_id | Identifier only; risk of memorizing clients instead of generalizing |
| content_hash_id | Identifier only; no predictive information |
| report_date | Not meaningful as a raw feature for this baseline; time-leakage risk if mishandled |
| Future performance metrics | Would leak information not available at prediction time |
| Label-derived columns | **Conditional on target — see section 3.** `gsc_clicks`/`gsc_avg_position` are flagged as candidate label-defining fields and must be excluded from any model whose target uses them |
| Product/internal flags | May encode business decisions already made; hidden leakage risk |

### Summary

Historical Search Console and Google Analytics features are used, all
identifiers/dates are excluded, and — the actual fix in this revision —
`gsc_clicks` and `gsc_avg_position` carry an explicit **conditional
leakage flag** that any downstream notebook must check against its own
target definition, instead of relying on a one-time "safe" label that can
go stale.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.

## Self-Check

- [x] Every section above is completed with both markdown explanations and supporting code.
- [x] The notebook runs from top to bottom without errors using **Runtime → Run all**.
- [x] No client names, URLs, private queries, or confidential information are included.
- [x] My conclusions use careful language such as **observed**, **measured**, **directional**, and **decision-support** instead of making causal claims.
- [x] The notebook has been saved under **work/notebooks/** in my GitHub repository and is ready for submission.